language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
gemfile:
  - gemfiles/Gemfile.3.2
  - gemfiles/Gemfile.4.0
  - gemfiles/Gemfile.4.1
script: bundle exec rspec spec
notifications:
  email:
    - fail@makandra.de
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: "1.8.7"
      gemfile: gemfiles/Gemfile.4.0
    - rvm: "1.8.7"
      gemfile: gemfiles/Gemfile.4.1
